-- Generated by nwg-displays on 2026-06-19 at 19:45:51. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2048x1280@120.0",
    position = "6x1080",
    scale = 1.07,
    mirror = "eDP-1"
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "6x1080",
    scale = 1.0,
    mirror = "eDP-1"
})
