#                                    !!WINDOW RULES!!                               #
# --------------------------------------------------------------------------------- #
#                                    !!WINDOW RULES!!                               #

# Increase default size of okular file opener
windowrule = float true, size 1280 720 override, match:class ^(okular)$, match:title ^(Open Document)

windowrule = float true, match:class ^(nwg-displays)$
windowrule = float true, match:class ^(clipse)$
windowrule = group deny, match:class ^(clipse)$

windowrule = size 300 500, match:class ^(clipse)$
windowrule = float true, match:class ^(sddm-conf)$
windowrule = float true, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float true, size 100 100 override, match:class ^(blueman-manager)$
windowrule = float true, match:class ^(org.kde.plasmashell)$
windowrule = float true, match:class ^(com.vixalien.sticky)$

windowrule = float true, size 100 100 override, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = pin true, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$

windowrule = float true, match:class ^([yY]ad)$

windowrule = tile on, match:class ^(MATLAB)

# Should only apply when the terminal is float trueing
windowrule = size 500 400 override, match:class ^(kitty)$
